PKGS=sdl2 glew gl
CC=clang
#OPT=-Ofast
OPT=-O0 -ggdb3
CFLAGS=--std=c99 $(OPT) -Wall $(shell pkg-config $(PKGS) --cflags) -DBUILD_LINUX
LINK=-lm $(shell pkg-config $(PKGS) --libs)
EXE=stub

include Makefile.common
