CC=clang
#OPT=-Ofast
OPT=-O0 -ggdb3
CFLAGS=--std=c99 $(OPT) -Wall -I/Library/Frameworks/SDL2.framework/Headers -I/System/Library/Frameworks/OpenGL.framework/Headers -DBUILD_OSX
LINK=-lm -framework SDL2 -framework OpenGL
EXE=stub

include Makefile.common

